# Generated by Django 4.1.7 on 2023-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='garage',
            field=models.IntegerField(default=0),
        ),
    ]
