# Generated by Django 3.2.10 on 2022-02-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_allowednumber'),
        ('users', '0002_useraccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='communaute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.communaute'),
        ),
    ]
