# Generated by Django 3.2.10 on 2022-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_communaute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Whats'app"),
        ),
    ]
