version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/yattblog
hooks:
  BeforeInstall:
   - location: utils_shortcuts/clean_up
     timeout: 200
     runas: root
  AfterInstall:
   - location: utils_shortcuts/prepareVenv_and_up_docker
     timeout: 300
     runas: root
