version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/yattblog
hooks:
  BeforeInstall:
   - location: utils_shortcuts/clean_up
     timeout: 7
     runas: root
  AfterInstall:
   # - location: utils_shortcuts/clean_up_docker_none
   - location: utils_shortcuts/prepareVenv_and_up_docker
     timeout: 600
     runas: root
