version: '3.8'

services:
    web:
        container_name: yattblog_django
        depends_on:
          - db
    db:
        image: postgres:12-alpine
        container_name: yattblog_db
    redis:
        image: redis:alpine
        ports:
            - 6379
