version: '3.8'

services:
    web:
        container_name: yattblog_django
        build: .
        command: python /home/alassane/yattblog/manage.py runserver 0.0.0.0:8000
        env_file:
            - variables.env # content env variable for databases and django
        volumes:
            - yattblog_django_data:/home/alassane/yattblog/
        ports:
            - 8000:8000
        depends_on:
          - db
    db:
        image: postgres:12-alpine
        container_name: yattblog_postgres
        volumes:
            - yattblog_postgres_data:/var/lib/postgresql/data/
        env_file:
            - variables.env # content env variable for databases and django

volumes:
    yattblog_postgres_data:
    yattblog_django_data:
