version: '3.8'

services:
    web:
        container_name: yattblog_django
        build:
            context: ./
            dockerfile: Dockerfile.prod
        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
        env_file:
            - ./.env.prod.env # content env variable for databases and django
        ports:
            - 8000:8000
        depends_on:
          - db
    db:
        image: postgres:12-alpine
        container_name: yattblog_postgres
        volumes:
            - yattblog_postgres:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.env # content env variable for databases and django
    cache:
      environment:
        TTL: '500'

volumes:
    yattblog_postgres:
    yattblog:
