version: '3.8'

services:
    web:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile.prod
        command: >
            bash -c "gunicorn backend.wsgi:application --bind 0.0.0.0:7000 &&
                     celery -A backend worker -l info"
        env_file:
            - ./.env_file/staging/.staging.celery # content env variable for databases and django
        volumes:
          - static_volume:/home/alassane/yattblog/staticfiles
          - media_volume:/home/alassane/yattblog/mediafiles
          - .:/home/alassane/yattblog
        expose:
            - 8000
        depends_on:
          - db
          - redis
    db:
        image: postgres:12-alpine
        volumes:
            - yattblog_db_volume:/var/lib/postgresql/data/
        env_file:
            - ./.env_file/staging/.staging.db_ # content env variable for databases and django
    nginx-proxy: # Autogenerate a nginx-config to each container on same network with VIRTUAL_HOST set
        container_name: nginx-proxy
        build: nginx
        restart: always
        ports:
            - 443:443
            - 80:80
        volumes:
            - static_volume:/home/alassane/yattblog/staticfiles # saved
            - media_volume:/home/alassane/yattblog/mediafiles # saved
        depends_on:
            - web

volumes:
    yattblog_db_volume:
    static_volume:
    media_volume:
