version: '3.8'

services:
    web:
        build: .
        command: python /home/alassane/yattblog/manage.py runserver 0.0.0.0:7000
        env_file:
            - ./.docker_venv.env # content env variable for databases and django
        ports:
            - 7000:7000
    db:
        volumes:
            - yattblog_postgres:/var/lib/postgresql/data/
        env_file:
            - ./.docker_venv.env # content env variable for databases and django
    cache:
      ports:
        - 6379:6379

volumes:
    yattblog_postgres:
