version: '3.8'

services:
    web:
        container_name: yattblog_django
        build:
            context: ./
            dockerfile: Dockerfile.prod
        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
        env_file:
            - ./.env.prod.env # content env variable for databases and django
        volumes:
          - static_volume:/home/alassane/yattblog/staticfiles
          - media_volume:/home/alassane/yattblog/mediafiles
        expose:
            - 8000
        depends_on:
          - db
    db:
        image: postgres:12-alpine
        container_name: yattblog_postgres
        volumes:
            - yattblog_postgres:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.env # content env variable for databases and django
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/alassane/yattblog/staticfiles
            - media_volume:/home/alassane/yattblog/mediafiles
        ports:
            - 1337:80
        depends_on:
            - web
    cache:
      environment:
        TTL: '500'


volumes:
    yattblog_postgres:
    static_volume:
    media_volume:
