version: '3.8'

services:
    web_student:
        depends_on:
          - db_student
    db_student:
        image: postgres:12-alpine

    redis:
        image: redis:alpine
        ports:
            - 6379
