# Generated by Django 4.1.7 on 2023-03-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owned_apartments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.apartment'),
        ),
    ]
