# Generated by Django 4.1.7 on 2023-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_guest_remove_agent_rent_apartments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Guest'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Agent'),
        ),
    ]
