[django_test_curr_file]
    description = "Task: To test Django current file TestCase"
    command = "sh"
    args = ['utils-shortcuts/test_file.sh ${relativeFile}']
    isBackground = false
[django_test_curr_file.problemMatcher]
    useStdout = true
    errorformat = '%f:%l:%c\ %m'

[django_test_curr_app]
    description = "Task: To test Django application TestCase"
    command = "sh"
    args = ['utils-shortcuts/test_app.sh ${relativeFileDirname}']
    isBackground = false
[django_test_curr_app.problemMatcher]
    useStdout = true
    errorformat = '%f:%l:%c\ %m'

[django_test_project]
    description = "Task: To test Django project"
    command = "python manage.py test"
    args = []
    isBackground = false
[django_test_curr_app.problemMatcher]
    useStdout = true
    errorformat = '%f:%l:%c\ %m'

[django_run_server]
    description = "Task: To run Django server"
    command = "python manage.py runserver"
    args = []
    isBackground = false
[django_test_curr_app.problemMatcher]
    useStdout = true
    errorformat = '%f:%l:%c\ %m'
