# Generated by Django 3.2.10 on 2022-01-11 10:19

from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('site', models.TextField()),
                ('is_rented', models.BooleanField(default=False)),
                ('lessor_number', models.CharField(default='...', max_length=14, unique=True)),
                ('lessor_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['top', 'left'], default='appartement-default.jpg', force_format=None, keep_meta=True, quality=75, size=[350, 280], upload_to='appartements_images')),
            ],
        ),
    ]
