# Generated by Django 3.2.10 on 2022-02-02 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('site', models.TextField()),
                ('is_rented', models.BooleanField(default=False)),
                ('lessor_number', models.CharField(default='...', max_length=14, unique=True)),
                ('lessor_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['top', 'left'], default='appartement-default.jpg', force_format=None, keep_meta=True, quality=75, size=[350, 280], upload_to='appartements_images')),
            ],
        ),
        migrations.CreateModel(
            name='Communaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'association")),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', django_resized.forms.ResizedImageField(crop=['top', 'left'], default='profile-pic-default.jpg', force_format=None, keep_meta=True, quality=75, size=[200, 200], upload_to='profile_pic', verbose_name='Image du profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name="Whats'app")),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='student.communaute', verbose_name='Communauté')),
            ],
        ),
    ]
