# Generated by Django 3.2.10 on 2022-02-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowednumber',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name="Whats'app"),
        ),
    ]
