# Generated by Django 3.2.10 on 2022-01-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='lessor_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='lessor_number',
            field=models.IntegerField(default='...', unique=True),
        ),
    ]
