# Generated by Django 3.2.10 on 2022-02-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_communaute_useraccount_community'),
        ('student', '0002_alter_allowednumber_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communaute',
            new_name='Community',
        ),
        migrations.RenameField(
            model_name='allowednumber',
            old_name='communaute',
            new_name='community',
        ),
    ]
