# Generated by Django 3.2.10 on 2022-02-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_allowednumber_communaute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communaute',
            name='allowed_numbers',
        ),
        migrations.DeleteModel(
            name='AllowedNumber',
        ),
    ]
