# Generated by Django 3.2.10 on 2022-02-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220201_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name="Whats'app")),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='student.communaute', verbose_name='Communauté')),
            ],
        ),
    ]
