# Generated by Django 3.2.10 on 2022-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_appartment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='lessor_number',
            field=models.BigIntegerField(default='...', unique=True),
        ),
    ]
