# Generated by Django 3.2.10 on 2022-01-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_appartment_lessor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='lessor_number',
            field=models.CharField(default='...', max_length=14, unique=True),
        ),
    ]
