# Generated by Django 3.2.10 on 2022-01-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_appartment_lessor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
