# Generated by Django 3.2.10 on 2022-01-10 23:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_appartment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
